//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discussions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Claim()
        {
            this.Votes = new HashSet<Vote>();
            this.SubEvidences = new HashSet<SubEvidence>();
        }
    
        public long ClaimId { get; set; }
        public Nullable<long> QuestionId { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Claim1 { get; set; }
        public string Evidence { get; set; }
        public string Source { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vote> Votes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubEvidence> SubEvidences { get; set; }
    }
}
