//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discussions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public long VoteId { get; set; }
        public Nullable<long> ClaimId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<bool> Vote1 { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Claim Claim { get; set; }
        public virtual User User { get; set; }
    }
}
